# 02. Сетевой анализ

В этом ноутбуке строится formal core и считаются базовые сетевые метрики.

In [2]:
import os
import sys

os.chdir(r"C:\Users\senya\Downloads\russian-power-network-main (2)\russian-power-network-main")
sys.path.append(os.getcwd())

print(os.getcwd())

C:\Users\senya\Downloads\russian-power-network-main (2)\russian-power-network-main

In [3]:
from src.load_data import build_processed_tables
from src.build_graphs import build_core_formal_graph
from src.metrics import compute_centrality_table

nodes, edges = build_processed_tables(save=False)
G = build_core_formal_graph(nodes, edges)
centrality = compute_centrality_table(G)
centrality.head(20)

,kumu_id,label,node_type,contour,degree,degree_centrality,betweenness_centrality,closeness_centrality
0,org_president_rf,Институт Президента Российской Федерации,organization,ядро координации,65,0.231317,0.238016,0.328634
90,pos_prime_minister,Председатель Правительства Российской Федерации,position,None,27,0.096085,0.014198,0.235169
5,org_state_duma,Государственная Дума Федерального Собрания Рос...,organization,воспроизводство и легитимация,24,0.085409,0.008998,0.180942
4,org_government_rf,Правительство Российской Федерации,organization,исполнение и принуждение,19,0.067616,0.062850,0.224855
6,org_federation_council,Совет Федерации Федерального Собрания Российск...,organization,воспроизводство и легитимация,12,0.042705,0.003618,0.162580
12,org_fsb_rf,Федеральная служба безопасности Российской Фед...,organization,исполнение и принуждение,7,0.024911,0.021886,0.208968
122,pos_minister_health,Министр здравоохранения Российской Федерации,position,None,4,0.014235,0.003811,0.205616
119,pos_minister_digital,"Министр цифрового развития, связи и массовых к...",position,None,4,0.014235,0.003811,0.205616
120,pos_minister_energy,Министр энергетики Российской Федерации,position,None,4,0.014235,0.003811,0.205616
121,pos_minister_industry_trade,Министр промышленности и торговли Российской Ф...,position,None,4,0.014235,0.003811,0.205616
125,pos_minister_natural_resources,Министр природных ресурсов и экологии Российск...,position,None,4,0.014235,0.003811,0.205616
123,pos_minister_labor,Министр труда и социальной защиты Российской Ф...,position,None,4,0.014235,0.003811,0.205616
124,pos_minister_agriculture,Министр сельского хозяйства Российской Федерации,position,None,4,0.014235,0.003811,0.205616
117,pos_minister_justice,Министр юстиции Российской Федерации,position,None,4,0.014235,0.004068,0.206167
126,pos_minister_transport,Министр транспорта Российской Федерации,position,None,4,0.014235,0.003811,0.205616
127,pos_minister_construction,Министр строительства и жилищно-коммунального ...,position,None,4,0.014235,0.003811,0.205616
118,pos_minister_economy,Министр экономического развития Российской Фед...,position,None,4,0.014235,0.003811,0.205616
113,pos_dep_pm_patrushev,Заместитель Председателя Правительства Российс...,position,None,4,0.014235,0.003811,0.205616
116,pos_minister_foreign_affairs,Министр иностранных дел Российской Федерации,position,None,4,0.014235,0.004068,0.206167
115,pos_minister_finance,Министр финансов Российской Федерации,position,None,4,0.014235,0.003811,0.205616

In [4]:
from src.metrics import summarize_layers
summarize_layers(nodes, edges)

,nodes_total,edges_total,comention_nodes,core_nodes,overlay_nodes,comention_edges,core_edges,overlay_edges
0,522,1920,110,282,130,1422,448,50

In [5]:
centrality.sort_values('betweenness_centrality', ascending=False).head(20)

,kumu_id,label,node_type,contour,degree,degree_centrality,betweenness_centrality,closeness_centrality
0,org_president_rf,Институт Президента Российской Федерации,organization,ядро координации,65,0.231317,0.238016,0.328634
4,org_government_rf,Правительство Российской Федерации,organization,исполнение и принуждение,19,0.067616,0.062850,0.224855
12,org_fsb_rf,Федеральная служба безопасности Российской Фед...,organization,исполнение и принуждение,7,0.024911,0.021886,0.208968
90,pos_prime_minister,Председатель Правительства Российской Федерации,position,None,27,0.096085,0.014198,0.235169
88,pos_first_dep_head_ap,Первый заместитель Руководителя Администрации ...,position,None,2,0.007117,0.010981,0.205616
5,org_state_duma,Государственная Дума Федерального Собрания Рос...,organization,воспроизводство и легитимация,24,0.085409,0.008998,0.180942
95,pos_chair_supreme_court,Председатель Верховного Суда Российской Федерации,position,None,4,0.014235,0.007636,0.205616
189,prs_kiriyenko,Сергей Кириенко,person,None,3,0.010676,0.007397,0.149032
20,org_minfin,Министерство финансов Российской Федерации,organization,исполнение и принуждение,3,0.010676,0.007397,0.158885
154,pos_head_sub_ap_public_projects_novikov,Начальник Управления Президента Российской Фед...,position,None,2,0.007117,0.007372,0.204522
117,pos_minister_justice,Министр юстиции Российской Федерации,position,None,4,0.014235,0.004068,0.206167
116,pos_minister_foreign_affairs,Министр иностранных дел Российской Федерации,position,None,4,0.014235,0.004068,0.206167
135,pos_director_svr,Директор Службы внешней разведки Российской Фе...,position,None,3,0.010676,0.003950,0.204522
136,pos_minister_emergencies,Министр Российской Федерации по делам гражданс...,position,None,3,0.010676,0.003950,0.204522
143,pos_chair_accounts_chamber,Председатель Счетной палаты Российской Федерации,position,None,3,0.010676,0.003950,0.204522
114,pos_director_rosgvardiya,Директор Федеральной службы войск национальной...,position,None,3,0.010676,0.003950,0.204522
99,pos_minister_internal_affairs,Министр внутренних дел Российской Федерации,position,None,3,0.010676,0.003950,0.204522
94,pos_chair_constitutional_court,Председатель Конституционного Суда Российской ...,position,None,3,0.010676,0.003950,0.204522
98,pos_director_fsb,Директор Федеральной службы безопасности Росси...,position,None,3,0.010676,0.003950,0.204522
96,pos_prosecutor_general,Генеральный прокурор Российской Федерации,position,None,3,0.010676,0.003950,0.204522